### ISSUE TITLE
S-7.1: As a user, I want my next class to be displayed in my calendar.

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#28]
The calendar outputs the information of the next class.

Acceptance criteria: 
- [x] Prepare UI to accept calendar information
- [x] Backend for fetching calendar information ~~(connect, auth and fetch calendar from google)~~
- [x] The next class is displayed at the top of the menu

Details:
A list of the selected day’s classes is displayed when <Your Schedule> is pressed from the sidebar menu.
The user’s next class should be displayed at the top.

**Comment by Alex-Hayeur** [comment]
- [ ] Prepare UI to accept calendar information

- [ ] Backend for fetching calendar information

**Comment by WindOfRussia** [comment]
Instead of doing oauth for google calendar we leveraged a flutter plugin that lets us browse all calendars stored on the phone (both iOS and Android).

This is a much more elegant solution for a couple of reasons :
 - No constant api calls and no internet connection required
 - No need find ways to store api tokens across app launches (alternatively, asking users to login every time they open the app but that would be horrible)
 - Support any calendar that can be added to your mobile phone
 - Support both iOS and Android equally, not forcing users to use Gcal.

**Comment by WindOfRussia** [comment]
PSA: 
This only picks up calendars that have 'conco' or 'uni' in their name.
You can test by adding a new calendar in your emulators calendar app and adding some class events to that calendar.

@andrelegault you will need to login to your google account on the emulators for it to work properly.
@MichelRahme if you have a school calendar try logging in to you appleId to test
